name:                2d-array
version:             0.1.0.0
github:              "HarrisonMc555/2d-array"
license:             BSD3
author:              "Harrison McCullough"
maintainer:          "mccullough.harrison@gmail.com"
copyright:           "Copyright (c) 2018 Harrison McCullough"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HarrisonMc555/2d-array#readme>

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  2d-array-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2d-array

tests:
  2d-array-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2d-array
    - hspec
